//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./CourseWork/Grammar/GLSLParserFull.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="GLSLParserFull"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface IGLSLParserFullVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.translation_unit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTranslation_unit([NotNull] GLSLParserFull.Translation_unitContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.variable_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable_identifier([NotNull] GLSLParserFull.Variable_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.primary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrimary_expression([NotNull] GLSLParserFull.Primary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.postfix_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPostfix_expression([NotNull] GLSLParserFull.Postfix_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.field_selection"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitField_selection([NotNull] GLSLParserFull.Field_selectionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.integer_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInteger_expression([NotNull] GLSLParserFull.Integer_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_call"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call([NotNull] GLSLParserFull.Function_callContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_identifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_identifier([NotNull] GLSLParserFull.Function_identifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_call_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_call_parameters([NotNull] GLSLParserFull.Function_call_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.unary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_expression([NotNull] GLSLParserFull.Unary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.unary_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnary_operator([NotNull] GLSLParserFull.Unary_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.assignment_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_expression([NotNull] GLSLParserFull.Assignment_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.assignment_operator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAssignment_operator([NotNull] GLSLParserFull.Assignment_operatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.binary_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBinary_expression([NotNull] GLSLParserFull.Binary_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] GLSLParserFull.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.constant_expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant_expression([NotNull] GLSLParserFull.Constant_expressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] GLSLParserFull.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.identifier_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIdentifier_list([NotNull] GLSLParserFull.Identifier_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_prototype"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_prototype([NotNull] GLSLParserFull.Function_prototypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_parameters"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_parameters([NotNull] GLSLParserFull.Function_parametersContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.parameter_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declarator([NotNull] GLSLParserFull.Parameter_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.parameter_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_declaration([NotNull] GLSLParserFull.Parameter_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.parameter_type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitParameter_type_specifier([NotNull] GLSLParserFull.Parameter_type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.init_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInit_declarator_list([NotNull] GLSLParserFull.Init_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.single_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_declaration([NotNull] GLSLParserFull.Single_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.typeless_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitTypeless_declaration([NotNull] GLSLParserFull.Typeless_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.fully_specified_type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFully_specified_type([NotNull] GLSLParserFull.Fully_specified_typeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.invariant_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInvariant_qualifier([NotNull] GLSLParserFull.Invariant_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.interpolation_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInterpolation_qualifier([NotNull] GLSLParserFull.Interpolation_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.layout_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier([NotNull] GLSLParserFull.Layout_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.layout_qualifier_id_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id_list([NotNull] GLSLParserFull.Layout_qualifier_id_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.layout_qualifier_id"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitLayout_qualifier_id([NotNull] GLSLParserFull.Layout_qualifier_idContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.precise_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecise_qualifier([NotNull] GLSLParserFull.Precise_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_qualifier([NotNull] GLSLParserFull.Type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.single_type_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSingle_type_qualifier([NotNull] GLSLParserFull.Single_type_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.storage_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStorage_qualifier([NotNull] GLSLParserFull.Storage_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.type_name_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name_list([NotNull] GLSLParserFull.Type_name_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.type_name"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_name([NotNull] GLSLParserFull.Type_nameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.type_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier([NotNull] GLSLParserFull.Type_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.array_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArray_specifier([NotNull] GLSLParserFull.Array_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.dimension"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDimension([NotNull] GLSLParserFull.DimensionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.type_specifier_nonarray"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType_specifier_nonarray([NotNull] GLSLParserFull.Type_specifier_nonarrayContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.precision_qualifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitPrecision_qualifier([NotNull] GLSLParserFull.Precision_qualifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.struct_specifier"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_specifier([NotNull] GLSLParserFull.Struct_specifierContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.struct_declaration_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration_list([NotNull] GLSLParserFull.Struct_declaration_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.struct_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declaration([NotNull] GLSLParserFull.Struct_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.struct_declarator_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator_list([NotNull] GLSLParserFull.Struct_declarator_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.struct_declarator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStruct_declarator([NotNull] GLSLParserFull.Struct_declaratorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.initializer"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer([NotNull] GLSLParserFull.InitializerContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.initializer_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInitializer_list([NotNull] GLSLParserFull.Initializer_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.declaration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration_statement([NotNull] GLSLParserFull.Declaration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement([NotNull] GLSLParserFull.StatementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.simple_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSimple_statement([NotNull] GLSLParserFull.Simple_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.compound_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement([NotNull] GLSLParserFull.Compound_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_no_new_scope([NotNull] GLSLParserFull.Statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.compound_statement_no_new_scope"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompound_statement_no_new_scope([NotNull] GLSLParserFull.Compound_statement_no_new_scopeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.statement_list"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitStatement_list([NotNull] GLSLParserFull.Statement_listContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.expression_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression_statement([NotNull] GLSLParserFull.Expression_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.selection_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_statement([NotNull] GLSLParserFull.Selection_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.selection_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSelection_rest_statement([NotNull] GLSLParserFull.Selection_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.condition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCondition([NotNull] GLSLParserFull.ConditionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.switch_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSwitch_statement([NotNull] GLSLParserFull.Switch_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.case_label"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCase_label([NotNull] GLSLParserFull.Case_labelContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.iteration_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitIteration_statement([NotNull] GLSLParserFull.Iteration_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.for_init_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_init_statement([NotNull] GLSLParserFull.For_init_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.for_rest_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFor_rest_statement([NotNull] GLSLParserFull.For_rest_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.jump_statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitJump_statement([NotNull] GLSLParserFull.Jump_statementContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.external_declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExternal_declaration([NotNull] GLSLParserFull.External_declarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="GLSLParserFull.function_definition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunction_definition([NotNull] GLSLParserFull.Function_definitionContext context);
}
