CONST      : 'const';
IN         : 'in';
OUT        : 'out';
INOUT      : 'inout';
UNIFORM    : 'uniform';
BUFFER     : 'buffer';
READONLY   : 'readonly';
STRUCT     : 'struct';
VOID       : 'void';
BOOL       : 'bool';
INT        : 'int';
UINT       : 'uint';
FLOAT      : 'float';
DOUBLE     : 'double';
VEC2       : 'vec2';
VEC3       : 'vec3';
VEC4       : 'vec4';
DVEC2      : 'dvec2';
DVEC3      : 'dvec3';
DVEC4      : 'dvec4';
TRUE       : 'true';
FALSE      : 'false';
IF         : 'if';
ELSE       : 'else';
SWITCH     : 'switch';
CASE       : 'case';
DEFAULT    : 'default';
WHILE      : 'while';
DO         : 'do';
FOR        : 'for';
BREAK      : 'break';
CONTINUE   : 'continue';
RETURN     : 'return';
DISCARD    : 'discard';

PLUS       : '+';
DASH       : '-';
STAR       : '*';
SLASH      : '/';
PERCENT    : '%';
INC_OP     : '++';
DEC_OP     : '--';
ASSIGN     : '=';
ADD_ASSIGN : '+=';
SUB_ASSIGN : '-=';
MUL_ASSIGN : '*=';
DIV_ASSIGN : '/=';
MOD_ASSIGN : '%=';
AND_ASSIGN : '&=';
OR_ASSIGN  : '|=';
XOR_ASSIGN : '^=';
LEFT_ASSIGN: '<<=';
RIGHT_ASSIGN: '>>=';
EQ_OP      : '==';
NE_OP      : '!=';
LE_OP      : '<=';
GE_OP      : '>=';
LEFT_OP    : '<<';
RIGHT_OP   : '>>';
AND_OP     : '&&';
OR_OP      : '||';
XOR_OP     : '^^';
AMPERSAND  : '&';
VERTICAL_BAR: '|';
CARET      : '^';
BANG       : '!';
TILDE      : '~';
QUESTION   : '?';
COLON      : ':';
COMMA      : ',';
SEMICOLON  : ';';
DOT        : '.';
LEFT_PAREN : '(';
RIGHT_PAREN: ')';
LEFT_BRACKET: '[';
RIGHT_BRACKET: ']';
LEFT_BRACE : '{';
RIGHT_BRACE: '}';
LEFT_ANGLE : '<';
RIGHT_ANGLE: '>';

INT_CONST    : [0-9]+;
UINT_CONST   : [0-9]+ [uU];
FLOAT_CONST  : [0-9]+ '.' [0-9]* ([eE][+-]?[0-9]+)? [fF]?
             | '.' [0-9]+ ([eE][+-]?[0-9]+)? [fF]?
             | [0-9]+ [eE][+-]?[0-9]+ [fF]?;
DOUBLE_CONST : [0-9]+ '.' [0-9]* ([eE][+-]?[0-9]+)? [lL][fF]?;
IDENTIFIER   : [a-zA-Z_][a-zA-Z0-9_]*;

LINE_COMMENT   : '//' ~[\r\n]*;
BLOCK_COMMENT  : '/*' .*? '*/';

WS : [ \t\r\n]+ -> skip;